flask_todo_vue/flask_server/models/todo.py
import time

from models import Model
from utils import formatted_time, log


class Todo(Model):
    """
    针对数据 TODO
    要做 4 件事情
    C create 创建数据
    R read 读取数据
    U update 更新数据
    D delete 删除数据

    Todo.new() 来创建一个 todo
    """

    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            'task',
            'created_time',
            'updated_time',
        ]
        return names

    @classmethod
    def new(cls, form):
        m = super().new(form)
        #t = int(time.time())
        t = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())
        m.created_time = t
        m.updated_time = t
        m.save()
        return m

    @classmethod
    def update(cls, id, form):
        m = super().update(id, form)
        log('todo update', m)
        m.updated_time = time.strftime("%Y-%m-%d %H:%M:%S",time.localtime())
        m.save()
        return m

    def formatted_created_time(self):
        return formatted_time(self.created_time)

    def formatted_updated_time(self):
        return formatted_time(self.updated_time)

flask_todo_vue/flask_server/routes/api_user.py
from flask import (
    redirect,
    Blueprint,
    request,
    session,
    url_for,
    make_response
)

from utils import log
from models.user import User

main = Blueprint('user_api', __name__)


@main.route('/login', methods=['POST'])
def login():
    """
    登录页面的路由函数
    """
    log('login, cookies', request.cookies)
    form = request.form
    u = User.new(form)
    if u.validate_login():
        u = User.find_by(username=u.username)
        # 登录后定向到 /
        # cookie
        # response = make_response(redirect(url_for('static.index')))
        # response.set_cookie('user_id', str(u.id))
        # return response
        session['user_id'] = u.id
        return redirect(url_for('static.index'))
    else:
        return redirect(url_for('user.login'))


@main.route('/register', methods=['POST'])
def register():
    """
    注册页面的路由函数
    """
    form = request.form
    u = User.new(form)
    if u.validate_register():
        # 注册成功再保存
        u.save()
        # 注册成功后 定向到登录页面
        return redirect(url_for('user.login'))
    else:
        # 注册失败 定向到注册页面
        return redirect(url_for('user.register'))

flask_todo_vue/flask_server/routes/routes_blog.py
from flask import (
    render_template,
    Blueprint,
    request,
)

# 创建一个蓝图对象
# 路由都定义在蓝图对象中
# 然后再 flask 主代码中 注册蓝图 来使用
# 第一个参数是蓝图的名字，类似namespace的作用
# 第二个参数是套路
main = Blueprint('blog', __name__)


@main.route('/index')
def index():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('blog_index.html')


@main.route('/new')
def new():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('blog_new.html')

@main.route('/detail')
def detail():
    """
    主页的处理函数, 返回主页的响应
    """
    blog_id = request.args.get('id')
    return render_template('blog_detail.html', blog_id=blog_id)

flask_todo_vue/flask_server/routes/routes_todo.py
from flask import (
    render_template,
    Blueprint,
)

# 创建一个蓝图对象
# 路由都定义在蓝图对象中
# 然后再 flask 主代码中 注册蓝图 来使用
# 第一个参数是蓝图的名字，类似namespace的作用
# 第二个参数是套路
main = Blueprint('todo', __name__)


@main.route('/index')
def index():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('todo_vue.html')

flask_todo_vue/flask_server/templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新建博客</title>
</head>
<body>
        {# 渲染模板的时候应该传一个blog id进来，不然无法 知道评论属于哪个blog #}
        <div class="gua-center-block gua-block" id="id-blog-cell" data-id={{ blog_id }}>
            <h1 id="id-blog-title" class="gua-center"></h1>
            {#  markdown 以后添加 #}
            <div id="id-blog-content" class="markdown-body"></div>
        </div>
        <div class="gua-center">
            <textarea id="id-input-content" name="content" placeholder="正文"></textarea>
            <br>
            <button id="id-button-add" class="pure-button pure-button-primary">发表评论</button>
            <br>
        </div>
        <table class="gua-center-block pure-table pure-table-striped">
            <thead>
                <tr>
                    <th>content</th>
                    <th>Updated Time</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody id="id-comment-list" >

            </tbody>
        </table>
</body>
    <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='markdown.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='base.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog.css') }}" rel="stylesheet">
    <script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
    <script src='{{ url_for('static', filename='base.js') }}'></script>
    <script src='{{ url_for('static', filename='blog_detail.js') }}'></script>
    <script src='{{ url_for('static', filename='comment.js') }}'></script>
</html>

flask_todo_vue/flask_server/templates/blog_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog</title>
</head>
<body>
    <h1 class="gua-center">blog首页</h1>
    <div class="gua-center">
        <a href="{{ url_for('blog.new') }}" class="pure-button pure-button-primary">新建</a>
    </div>
            <table class="gua-center-block pure-table pure-table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Updated Time</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody id="id-blog-list" >

            </tbody>
        </table>

</body>
<link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
<link href="{{ url_for('static', filename='base.css') }}" rel="stylesheet">
<script src='{{ url_for('static', filename='base.js') }}'></script>
<script src='{{ url_for('static', filename='blog_index.js') }}'></script>
</html>

flask_todo_vue/flask_server/templates/blog_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog new</title>
</head>
<body>
    <h1 class="gua-center">blog</h1>
    <div class="gua-center pure-form">
        <input id="id-input-title" name="title" placeholder="标题">
        <br>
        <textarea id="id-input-content" name="content" placeholder="正文"></textarea>
        <br>
        <button id="id-button-add" class="pure-button pure-button-primary">发表</button>
    <div/>
</body>
<link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
<link href="{{ url_for('static', filename='base.css') }}" rel="stylesheet">
<script src='{{ url_for('static', filename='base.js') }}'></script>
<script src='{{ url_for('static', filename='blog_new.js') }}'></script>
</html>

flask_todo_vue/flask_server/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>flask todo&blog主页</title>
</head>
<body>
    <h1>Hello {{username}}</h1>
    <img src="/static/doge.gif"/>
    <img src="/static/doge1.jpg"/>
    <img src="/static/doge2.gif"/>
    <br>
    <a href="{{ url_for('user.login') }}">Login</a>
    <a href="{{ url_for('user.register') }}">Register</a>
    <a href="{{ url_for('todo.index') }}">Todo</a>
    <a href="{{ url_for('blog.index') }}">Blog</a>
</body>
</html>

flask_todo_vue/flask_server/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册登录页面</title>
</head>
<body>
    <h1>登录</h1>
    <h2>你好 {{username}}</h2>
    <form action="{{ url_for('user_api.login') }}" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button class="pure-button pure-button-primary" type="submit">登录</button>
    </form>
    <h3>{{result}}</h3>
</body>
<link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
</html>

flask_todo_vue/flask_server/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    <h1>注册</h1>
    <form action="/register" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button type="submit">注册</button>
    </form>
</body>
</html>

flask_todo_vue/flask_server/templates/todo.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ajax flask todo with css</title>
    </head>
    <body>
        <h1 class="gua-center">ajax flask todo with css</h1>
        <div class="gua-center pure-form">
            <input id='id-input-todo'>
            <button id='id-button-add' class="pure-button pure-button-primary">添加</button>
        </div>
        <table class="gua-center-block pure-table pure-table-striped">
            <thead>
                <tr>
                    <th>Content</th>
                    <th>Updated Time</th>
                    <th>Delete</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody id="id-todo-list" >

            </tbody>
        </table>
        <!-- 这是处理静态文件的套路 -->
        <!-- base.js 放了公共的函数 -->
        <!-- 按顺序引入 2 个 js 文件, 后面的 js 文件就能使用前面的文件中的函数了 -->
        <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='base.css') }}" rel="stylesheet">
        <script src='{{ url_for('static', filename='base.js') }}'></script>
        <script src='{{ url_for('static', filename='todo.js') }}'></script>
    </body>
</html>

flask_todo_vue/flask_server/templates/todo_vue.html
<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>appfront</title><link href=/static/css/app.7ba9b6b5b81fc2abdfb2df8f7efde02b.css rel=stylesheet></head><body><div id=app></div><script type=text/javascript src=/static/js/manifest.2ae2e69a05c33dfc65f8.js></script><script type=text/javascript src=/static/js/vendor.7eaa77844932141440ae.js></script><script type=text/javascript src=/static/js/app.25fe0833bfb60bd0e151.js></script></body></html>